package p1;
class Parent{
	Parent(int a){
		System.out.println("This is Parent class constructor");
	}
}
public class Child extends Parent{
	Child()
	{
		super(456); //explicitly generated by compiler
		System.out.println("this is child class Constructor");
	}
	public static void main(String[] args) {
		new Child();
	}
}


